export default JSON.stringify({
    "name": "GHC Theme",
    "isInverted": false,
    "theme": {
      "primaryText": "#333",
      "bodyText": "#333",
      "neutralLighterAlt": "#f8f8f8",
      "neutralLighter": "#f4f4f4",
      "neutralLight": "#eaeaea",
      "neutralQuaternaryAlt": "#dadada",
      "neutralQuaternary": "#d0d0d0",
      "neutralTertiaryAlt": "#c8c8c8",
      "neutralTertiary": "#c2c2c2",
      "neutralSecondary": "#858585",
      "neutralPrimaryAlt": "#4b4b4b",
      "neutralPrimary": "#333",
      "neutralDark": "#272727",
      "black": "#1a1a1a",
      "white": "#fff",
      "disabledBackground": "#f4f4f4",
      "disabledText": "#c8c8c8",
      "themePrimary": "#E6003E",
      "themeLight": "#EC567E",
      "themeLighter": "#F5A9BD",
      "themeDark": "#BA0A39",
      "themeDarker": "#830728",
      "themeSecondary": "#E6003E",
      "themeLighterAlt": "#EC567E",
      "themeDarkAlt": "#E6003E",
      "themeTertiary": "#4B848E",
      "accent": "#719D64",
      "bodyBackground": "#FFFFFF",
      "primaryBackground": "#FFFFFF"
    }
  }, null, "\t");